name: cd

on: 
    workflow_run: 
        workflows: ["ci"]
        types:
            - completed

jobs:
    start:
        runs-on: node_54

        steps:
            - name: Kéo Image mới nhất từ Docker Hub
              run: sudo docker pull luquocphap/img-gateway:latest

            - name: Dừng và xóa container cũ bằng Compose
              working-directory: /home/luquocphap/nestjs
              run: sudo docker compose down

            - name: Chạy lại hệ thống với Image mới
              working-directory: /home/luquocphap/nestjs
              run: sudo docker compose up -d

